"""initial schema

Revision ID: 951ea56e5958
Revises: 
Create Date: 2026-06-05 15:43:23.151465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '951ea56e5958'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('core', 'extended', name='district_level', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('field_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.Enum('enrollment', 'promotion', name='record_type', native_enum=False), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('public', 'private', name='school_type', native_enum=False), nullable=False),
    sa.Column('level', sa.Enum('primary', 'middle', 'nine_year', name='school_level', native_enum=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('gov_website', 'school_website', 'wechat', 'pdf', name='source_type', native_enum=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('parser_strategy', sa.Enum('rule', 'llm', 'hybrid', name='parser_strategy', native_enum=False), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='job_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('docs_fetched', sa.Integer(), nullable=False),
    sa.Column('changes_detected', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('raw_file_path', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('policy_type', sa.Enum('school_enrollment', 'gov_policy', 'district_mapping', name='policy_type', native_enum=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_doc_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('target_school_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_doc_id', sa.Uuid(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['target_school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.Enum('enrollment', 'promotion', name='record_type', native_enum=False), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_doc_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_doc_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_versions')
    op.drop_table('promotion_policies')
    op.drop_table('enrollment_policies')
    op.drop_table('raw_documents')
    op.drop_table('job_runs')
    op.drop_table('data_sources')
    op.drop_table('schools')
    op.drop_table('field_changes')
    op.drop_table('districts')
    # ### end Alembic commands ###
